# Generated by Django 4.2.3 on 2023-07-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_vaga', models.CharField(max_length=100)),
                ('faixa_salarial', models.CharField(max_length=100)),
                ('escolaridade_vaga', models.TextField(max_length=100)),
            ],
        ),
    ]
