# Generated by Django 4.2.3 on 2023-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vagas_escolaridade_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
