# Generated by Django 4.2.3 on 2023-07-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vagas_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='faixa_salarial',
            field=models.CharField(choices=[('ATÉ 1.000', 'Até 1.000'), ('DE 1.000 a 2.000', 'De 1.000 a 2.000'), ('DE 2.000 a 3.000', 'De 2.000 a 3.000'), ('ACIMA de 3.000', 'Acima de 3.000')], default='', max_length=100),
        ),
    ]
