# Generated by Django 4.2.3 on 2023-07-11 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vaga_data_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='legenda',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
