# Generated by Django 4.2.3 on 2023-07-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vaga_legenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='data_publicada',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='legenda',
        ),
    ]
