# Generated by Django 4.2.3 on 2023-07-11 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_vaga_data_publicada_remove_vaga_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_publicada',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
