# Generated by Django 4.2.3 on 2023-07-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vaga_data_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='data_publicada',
        ),
    ]
