# Generated by Django 4.2.3 on 2023-07-11 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_vaga_data_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_publicada',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vaga',
            name='descricao_vaga',
            field=models.TextField(default=''),
        ),
    ]
