# Generated by Django 4.2.3 on 2023-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_vaga_data_publicada_vaga_descricao_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_publicada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
