# Generated by Django 4.2.3 on 2023-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_vaga_data_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade_vaga',
            field=models.TextField(choices=[('ENSINO FUNDAMENTAL', 'Ensino fundamental'), ('ENSINO MÉDIO', 'Ensino médio'), ('TECNÓLOGO', 'Tecnólogo'), ('ENSINO SUPERIOR', 'Ensino Superior'), ('PÓS / MBA / MESTRADO', 'Pós / MBA / Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='faixa_salarial',
            field=models.CharField(choices=[('ATÉ 1.000', 'Até 1.000'), ('DE 1.000 a 2.000', 'De 1.000 a 2.000'), ('DE 2.000 a 3.000', 'De 2.000 a 3.000'), ('ACIMA de 3.000', 'Acima de 3.000')], max_length=100),
        ),
    ]
