# Generated by Django 4.2.3 on 2023-07-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_vaga_escolaridade_vaga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='escolaridade_vaga',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='faixa_salarial',
            field=models.CharField(max_length=100),
        ),
    ]
