# Generated by Django 4.2.3 on 2023-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vaga_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
